import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Theme = 'light' | 'dark';
type Language = 'en' | 'ru';

interface ThemeContextType {
  theme: Theme;
  language: Language;
  toggleTheme: () => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const ThemeContext = createContext<ThemeContextType | undefined>(undefined);

export const useTheme = () => {
  const context = useContext(ThemeContext);
  if (context === undefined) {
    throw new Error('useTheme must be used within a ThemeProvider');
  }
  return context;
};

// Translations
const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.payments': 'Payments',
    'nav.expenses': 'Expenses',
    'nav.students': 'Students',
    'nav.studentsList': 'Students List',
    'nav.teachers': 'Teachers',
    'nav.parents': 'Parents',
    'nav.attendance': 'Attendance',
    'nav.schedule': 'Schedule',
    'nav.violations': 'Incidents',
    'nav.employees': 'Employees',
    'nav.events': 'Events',
    'nav.reports': 'Reports',
    'nav.notifications': 'Notifications',
    'nav.support': 'Support',
    'nav.settings': 'Settings',
    'nav.activity': 'Activity Log',
    'nav.logout': 'Logout',
    
    // Common
    'common.search': 'Search',
    'common.search.placeholder': 'Search...',
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.saving': 'Saving...',
    'common.cancel': 'Cancel',
    'common.export': 'Export',
    'common.loading': 'Loading...',
    'common.noData': 'No data available',
    'common.noDocuments': 'No documents uploaded',
    'common.viewAll': 'View All',
    'common.viewDetails': 'View Details',
    'common.sendMessage': 'Send Message',
    'common.male': 'Male',
    'common.female': 'Female',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.title': 'CEO Dashboard',
    'dashboard.dateSettings': 'Date Settings',
    'dashboard.revenue': 'Total Revenue',
    'dashboard.students': 'Active Students',
    'dashboard.pending': 'Pending Payments',
    'dashboard.expenses': 'Expenses',
    'dashboard.events': 'This Month\'s Events',
    'dashboard.debtors': 'Outstanding Debtors',
    'dashboard.activity': 'Staff Activity',
    'dashboard.recentTransactions': 'Recent Transactions',
    'dashboard.viewAllTransactions': 'View All Transactions',
    'dashboard.viewAllEvents': 'View All Events',
    'dashboard.manageDebtors': 'Manage Debtors',
    'dashboard.viewActivityLog': 'View Activity Log',
    
    // Students
    'students.title': 'Students Management',
    'students.subtitle': 'Comprehensive student information and performance tracking',
    'students.addStudent': 'Add Student',
    'students.groupsChart': 'Distribution by Groups',
    'students.clickForDetails': 'Click on a bar to view group details',
    'students.totalStudents': 'Total Students',
    'students.totalRevenue': 'Total Revenue',
    'students.totalOwed': 'Total Owed',
    'students.avgAttendance': 'Avg Attendance',
    'students.debtCases': 'Debt Cases',
    'students.active': 'Active',
    'students.allTime': 'All time',
    'students.outstanding': 'Outstanding',
    'students.acrossAll': 'Across all students',
    'students.requiresAttention': 'Requires attention',
    'students.allStudents': 'All Students',
    'students.withDebt': 'With Debt',
    'students.suspended': 'Suspended',
    'students.graduated': 'Graduated',
    'students.searchPlaceholder': 'Search by name, ID, or email...',
    'students.allGrades': 'All Grades',
    'students.grade': 'Grade',
    'students.allStatus': 'All Status',
    'students.status': 'Status',
    'students.allPerformance': 'All Performance',
    'students.academicStatus': 'Academic Status',
    'students.excellent': 'Excellent',
    'students.good': 'Good',
    'students.average': 'Average',
    'students.needsImprovement': 'Needs Improvement',
    'students.attendance': 'Attendance',
    'students.gpa': 'GPA',
    'students.balance': 'Balance',
    
    // Landing Page
    'landing.title': 'Westminster International School Tashkent',
    'landing.subtitle': 'Financial & Admin Portal',
    'landing.administration': 'Administration',
    'landing.parents': 'Parents',
    'landing.demo.ceo': 'Demo as CEO',
    'landing.demo.accountant': 'Demo as Accountant',
    'landing.demo.cashier': 'Demo as Cashier',
    'landing.demo.parent': 'Demo as Parent',
    
    // Login
    'login.title': 'Sign In',
    'login.email': 'Email or Phone',
    'login.password': 'Password',
    'login.signin': 'Sign In',
    'login.forgot': 'Forgot password?',
    'login.footer': 'By signing in, you agree to our Terms of Service and Privacy Policy.',
    
    // Teachers
    'teachers.title': 'Teachers Management',
    'teachers.subtitle': 'Comprehensive teacher information and class assignments',
    'teachers.addTeacher': 'Add Teacher',
    'teachers.departmentChart': 'Distribution by Department',
    'teachers.totalTeachers': 'Total Teachers',
    'teachers.active': 'active',
    'teachers.onLeave': 'On Leave',
    'teachers.currentlyAway': 'Currently away',
    'teachers.departments': 'Departments',
    'teachers.uniqueDepts': 'Unique departments',
    'teachers.senSpecialists': 'SEN Specialists',
    'teachers.certified': 'Certified',
    'teachers.allTeachers': 'All Teachers',
    'teachers.former': 'Former Staff',
    'teachers.searchPlaceholder': 'Search by name, ID, email, or department...',
    'teachers.allDepartments': 'All Departments',
    'teachers.department': 'Department',
    'teachers.allRoles': 'All Roles',
    'teachers.role': 'Role',
    'teachers.allDivisions': 'All Divisions',
    'teachers.division': 'Division',
    'teachers.includeFormer': 'Include former staff',
    'teachers.noDepartment': 'No Department',
    'teachers.noTeachersFound': 'No teachers found matching your criteria',
    'teachers.roleTeacher': 'Teacher',
    'teachers.roleSeniorTeacher': 'Senior Teacher',
    'teachers.roleCoordinator': 'Coordinator',
    'teachers.roleHOD': 'Head of Department',
    'teachers.divisionPrimary': 'Primary',
    'teachers.divisionSecondary': 'Secondary',
    'teachers.divisionSixthForm': 'Sixth Form',
    'teachers.personal': 'Personal',
    'teachers.employment': 'Employment',
    'teachers.academic': 'Academic',
    'teachers.schedule': 'Schedule',
    'teachers.documents': 'Documents',
    'teachers.personalInfo': 'Personal Information',
    'teachers.preferredName': 'Preferred Name',
    'teachers.gender': 'Gender',
    'teachers.dateOfBirth': 'Date of Birth',
    'teachers.nationality': 'Nationality',
    'teachers.passportId': 'Passport/ID Number',
    'teachers.contactInfo': 'Contact Information',
    'teachers.employmentDetails': 'Employment Details',
    'teachers.employmentType': 'Employment Type',
    'teachers.staffCategory': 'Staff Category',
    'teachers.dates': 'Important Dates',
    'teachers.hiringDate': 'Hiring Date',
    'teachers.endDate': 'End Date',
    'teachers.qualifications': 'Qualifications',
    'teachers.certificationLevel': 'Certification Level',
    'teachers.senExpertise': 'SEN Expertise',
    'teachers.subjects': 'Subject Specialization',
    'teachers.schoolInfo': 'School Information',
    'teachers.schoolDivision': 'School Division',
    'teachers.houseDivision': 'House/Division',
    'teachers.teachingLoad': 'Teaching Load',
    'teachers.assignedClasses': 'Assigned Classes',
    'teachers.yearGroups': 'Year Groups',
    'teachers.tutorGroup': 'Tutor Group',
    'teachers.homeRoom': 'Home Room',
    'teachers.trainingRecords': 'Training Records',
    'teachers.notes': 'Notes',
    'teachers.generalDetails': 'General Details',
    'teachers.fullName': 'Full Name',
    'teachers.staffId': 'Staff ID',
    'teachers.selectGender': 'Select gender',
    'teachers.email': 'Email',
    'teachers.phone': 'Phone',
    'teachers.addressLine1': 'Address Line 1',
    'teachers.addressLine2': 'Address Line 2',
    'teachers.city': 'City',
    'teachers.country': 'Country',
    'teachers.postalCode': 'Postal Code',
    'teachers.status': 'Status',
    'teachers.statusActive': 'Active',
    'teachers.statusOnLeave': 'On Leave',
    'teachers.statusFormer': 'Former Staff',
    'teachers.fullTime': 'Full Time',
    'teachers.partTime': 'Part Time',
    'teachers.contract': 'Contract',
    'teachers.categoryAcademic': 'Academic',
    'teachers.categorySupport': 'Support',
    'teachers.categoryAdmin': 'Administration',
    'teachers.subjectsPlaceholder': 'e.g. Mathematics, Physics',
    'teachers.classesPlaceholder': 'e.g. 10A, 10B, 11A',
    'teachers.yearGroupsPlaceholder': 'e.g. 10, 11, 12',
    'teachers.validationError': 'Please fill in all required fields',
    'teachers.addSuccess': 'Teacher added successfully',
    'teachers.addError': 'Failed to add teacher',
  },
  ru: {
    // Navigation
    'nav.dashboard': 'Панель управления',
    'nav.payments': 'Платежи',
    'nav.expenses': 'Расходы',
    'nav.students': 'Студенты',
    'nav.studentsList': 'Список студентов',
    'nav.parents': 'Родители',
    'nav.attendance': 'Посещаемость',
    'nav.schedule': 'Расписание',
    'nav.violations': 'Инциденты',
    'nav.employees': 'Сотрудники',
    'nav.events': 'События',
    'nav.reports': 'Отчёты',
    'nav.notifications': 'Уведомления',
    'nav.support': 'Поддержка',
    'nav.settings': 'Настройки',
    'nav.activity': 'Журнал активности',
    'nav.logout': 'Выйти',
    
    // Common
    'common.search': 'Поиск',
    'common.search.placeholder': 'Поиск...',
    'common.add': 'Добавить',
    'common.edit': 'Редактировать',
    'common.delete': 'Удалить',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.export': 'Экспорт',
    'common.loading': 'Загрузка...',
    'common.noData': 'Нет данных',
    'common.viewAll': 'Посмотреть все',
    'common.viewDetails': 'Подробности',
    'common.sendMessage': 'Отправить сообщение',
    
    // Dashboard
    'dashboard.welcome': 'Добро пожаловать',
    'dashboard.title': 'Панель CEO',
    'dashboard.dateSettings': 'Настройки даты',
    'dashboard.revenue': 'Общий доход',
    'dashboard.students': 'Активные студенты',
    'dashboard.pending': 'Ожидающие платежи',
    'dashboard.expenses': 'Расходы',
    'dashboard.events': 'События этого месяца',
    'dashboard.debtors': 'Должники',
    'dashboard.activity': 'Активность персонала',
    'dashboard.recentTransactions': 'Последние транзакции',
    'dashboard.viewAllTransactions': 'Посмотреть все транзакции',
    'dashboard.viewAllEvents': 'Посмотреть все события',
    'dashboard.manageDebtors': 'Управление должниками',
    'dashboard.viewActivityLog': 'Посмотреть журнал активности',
    
    // Students
    'students.title': 'Управление студентами',
    'students.subtitle': 'Комплексная информация о студентах и отслеживание успеваемости',
    'students.addStudent': 'Добавить студента',
    'students.groupsChart': 'Распределение по группам',
    'students.clickForDetails': 'Нажмите на столбец для просмотра деталей группы',
    'students.totalStudents': 'Всего студентов',
    'students.totalRevenue': 'Общий доход',
    'students.totalOwed': 'Всего задолженности',
    'students.avgAttendance': 'Ср. посещаемость',
    'students.debtCases': 'Должники',
    'students.active': 'Активные',
    'students.allTime': 'За всё время',
    'students.outstanding': 'Задолженность',
    'students.acrossAll': 'Все студенты',
    'students.requiresAttention': 'Требует внимания',
    'students.allStudents': 'Все студенты',
    'students.withDebt': 'С задолженностью',
    'students.suspended': 'Отстранены',
    'students.graduated': 'Выпускники',
    'students.searchPlaceholder': 'Поиск по имени, ID или email...',
    'students.allGrades': 'Все классы',
    'students.grade': 'Класс',
    'students.allStatus': 'Все статусы',
    'students.status': 'Статус',
    'students.allPerformance': 'Вся успеваемость',
    'students.academicStatus': 'Академический статус',
    'students.excellent': 'Отлично',
    'students.good': 'Хорошо',
    'students.average': 'Средне',
    'students.needsImprovement': 'Требует улучшения',
    'students.attendance': 'Посещаемость',
    'students.gpa': 'Средний балл',
    'students.balance': 'Баланс',
    
    // Landing Page
    'landing.title': 'Вестминстерская международная школа Ташкент',
    'landing.subtitle': 'Финансовый и административный портал',
    'landing.administration': 'Администрация',
    'landing.parents': 'Родители',
    'landing.demo.ceo': 'Демо как CEO',
    'landing.demo.accountant': 'Демо как бухгалтер',
    'landing.demo.cashier': 'Демо как кассир',
    'landing.demo.parent': 'Демо как родитель',
    
    // Login
    'login.title': 'Вход в систему',
    'login.email': 'Email или телефон',
    'login.password': 'Пароль',
    'login.signin': 'Войти',
    'login.forgot': 'Забыли пароль?',
    'login.footer': 'Входя в систему, вы соглашаетесь с нашими Условиями обслуживания и Политикой конфиденциальности.',
    
    // Teachers
    'nav.teachers': 'Учителя',
    'teachers.title': 'Управление учителями',
    'teachers.subtitle': 'Информация об учителях и назначениях классов',
    'teachers.addTeacher': 'Добавить учителя',
    'teachers.departmentChart': 'Распределение по отделам',
    'teachers.totalTeachers': 'Всего учителей',
    'teachers.active': 'активных',
    'teachers.onLeave': 'В отпуске',
    'teachers.currentlyAway': 'Сейчас отсутствуют',
    'teachers.departments': 'Отделы',
    'teachers.uniqueDepts': 'Уникальных отделов',
    'teachers.senSpecialists': 'Специалисты SEN',
    'teachers.certified': 'Сертифицированы',
    'teachers.allTeachers': 'Все учителя',
    'teachers.former': 'Бывшие сотрудники',
    'teachers.searchPlaceholder': 'Поиск по имени, ID, email или отделу...',
    'teachers.allDepartments': 'Все отделы',
    'teachers.department': 'Отдел',
    'teachers.allRoles': 'Все роли',
    'teachers.role': 'Роль',
    'teachers.allDivisions': 'Все подразделения',
    'teachers.division': 'Подразделение',
    'teachers.includeFormer': 'Включить бывших сотрудников',
    'teachers.noDepartment': 'Без отдела',
    'teachers.noTeachersFound': 'Учителя не найдены',
    'teachers.roleTeacher': 'Учитель',
    'teachers.roleSeniorTeacher': 'Старший учитель',
    'teachers.roleCoordinator': 'Координатор',
    'teachers.roleHOD': 'Заведующий отделом',
    'teachers.divisionPrimary': 'Начальная школа',
    'teachers.divisionSecondary': 'Средняя школа',
    'teachers.divisionSixthForm': 'Старшая школа',
    'teachers.personal': 'Личное',
    'teachers.employment': 'Трудоустройство',
    'teachers.academic': 'Академическое',
    'teachers.schedule': 'Расписание',
    'teachers.documents': 'Документы',
    'teachers.personalInfo': 'Личная информация',
    'teachers.preferredName': 'Предпочтительное имя',
    'teachers.gender': 'Пол',
    'teachers.dateOfBirth': 'Дата рождения',
    'teachers.nationality': 'Национальность',
    'teachers.passportId': 'Паспорт/ID',
    'teachers.contactInfo': 'Контактная информация',
    'teachers.employmentDetails': 'Детали трудоустройства',
    'teachers.employmentType': 'Тип занятости',
    'teachers.staffCategory': 'Категория персонала',
    'teachers.dates': 'Важные даты',
    'teachers.hiringDate': 'Дата найма',
    'teachers.endDate': 'Дата окончания',
    'teachers.qualifications': 'Квалификация',
    'teachers.certificationLevel': 'Уровень сертификации',
    'teachers.senExpertise': 'Экспертиза SEN',
    'teachers.subjects': 'Предметы',
    'teachers.schoolInfo': 'Школьная информация',
    'teachers.schoolDivision': 'Подразделение школы',
    'teachers.houseDivision': 'Дом/Отделение',
    'teachers.teachingLoad': 'Учебная нагрузка',
    'teachers.assignedClasses': 'Назначенные классы',
    'teachers.yearGroups': 'Годовые группы',
    'teachers.tutorGroup': 'Группа тьютора',
    'teachers.homeRoom': 'Домашний кабинет',
    'teachers.trainingRecords': 'Записи обучения',
    'teachers.notes': 'Заметки',
    'teachers.generalDetails': 'Общие данные',
    'teachers.fullName': 'Полное имя',
    'teachers.staffId': 'ID сотрудника',
    'teachers.selectGender': 'Выберите пол',
    'teachers.email': 'Email',
    'teachers.phone': 'Телефон',
    'teachers.addressLine1': 'Адрес (строка 1)',
    'teachers.addressLine2': 'Адрес (строка 2)',
    'teachers.city': 'Город',
    'teachers.country': 'Страна',
    'teachers.postalCode': 'Почтовый индекс',
    'teachers.status': 'Статус',
    'teachers.statusActive': 'Активный',
    'teachers.statusOnLeave': 'В отпуске',
    'teachers.statusFormer': 'Бывший сотрудник',
    'teachers.fullTime': 'Полная занятость',
    'teachers.partTime': 'Частичная занятость',
    'teachers.contract': 'Контракт',
    'teachers.categoryAcademic': 'Академический',
    'teachers.categorySupport': 'Поддержка',
    'teachers.categoryAdmin': 'Администрация',
    'teachers.subjectsPlaceholder': 'напр. Математика, Физика',
    'teachers.classesPlaceholder': 'напр. 10A, 10B, 11A',
    'teachers.yearGroupsPlaceholder': 'напр. 10, 11, 12',
    'teachers.validationError': 'Заполните все обязательные поля',
    'teachers.addSuccess': 'Учитель успешно добавлен',
    'teachers.addError': 'Ошибка добавления учителя',
    'common.saving': 'Сохранение...',
    'common.noDocuments': 'Документы не загружены',
    'common.male': 'Мужской',
    'common.female': 'Женский',
  },
};

interface ThemeProviderProps {
  children: ReactNode;
}

export const ThemeProvider: React.FC<ThemeProviderProps> = ({ children }) => {
  const [theme, setTheme] = useState<Theme>('light');
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const root = window.document.documentElement;
    root.classList.remove('light', 'dark');
    root.classList.add(theme);
  }, [theme]);

  const toggleTheme = () => {
    setTheme(prev => prev === 'light' ? 'dark' : 'light');
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ru' : 'en');
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  const value = {
    theme,
    language,
    toggleTheme,
    toggleLanguage,
    t,
  };

  return <ThemeContext.Provider value={value}>{children}</ThemeContext.Provider>;
};